spring:
  application:
    name: guoguo-client
server:
  port: 8006

eureka:
  instance:
    hostname: spring.application.name:${server.port}
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
#feign:
#  client:
#    config:
#      feignName:
#        encoder: com.tianjiaguo.site.server.codec.HelloEncoder
#        decoder: com.tianjiaguo.site.server.codec.HelloDecoder
